### ISSUE TITLE
Cant Run On Windows 7 32Bit

### ISSUE THREAD

**Issue by abbas381366** [ryanbekhen/nanoproxy#19]
hello
i want run it on windows 7 32 bit and get me this error ?
what is requirement to run it ?

![Screenshot 2024-05-27 090121](https://github.com/ryanbekhen/nanoproxy/assets/63393590/58d348fc-c59d-41ae-addc-18816d8fef01)

**Comment by abbas381366** [comment]
and for i386 get me this Error

![Screenshot 2024-05-27 090251](https://github.com/ryanbekhen/nanoproxy/assets/63393590/7aa41c5d-a19d-45ca-b316-9c606520822e)

**Comment by ryanbekhen** [comment]
@abbas381366 Thanks for use nanoproxy, may be i’ll try it on next week.
